### ISSUE TITLE
Dyable Catwalks

### ISSUE THREAD

**Issue by CTB33391** [TeamDmfMM/Catwalks-4#11]
See title. So cocoa beans could make them look rusty, cyan dye on glass catwalk could look like a Combine walkway (If you don't know who I mean, see [here](https://en.wikipedia.org/wiki/Combine_(Half-Life)))...
In fact, the different parts (frame, railing, floor) could receive different dyes. Aforementioned Combine walkway would be blue frame, blue railing and cyan floor. You'd do this in a block called the Suspended Transport Decorator (there, you can make that an in-joke if you want).

**Comment by dmf444** [comment]
While this seems fun, I can’t art. Also the amount of lag that would happen to layer colors on the catwalks would probably wake the game unplayable. I may revisit this in the future, but for now, it’s a no.
