### ISSUE TITLE
Suggestion: slightly higher handrails

### ISSUE THREAD

**Issue by Zygus42** [TeamDmfMM/Catwalks-4#15]
Would be nice if when you walk along a catwalk, you didn't just step over the railing and plunge to your death.  I would suggest making the handrails have the same block and a bit behavior that fences have so that you actually stay in the channel while you're walking.

**Comment by dmf444** [comment]
Agreed. I’ve been wanting to do that for a while

**Comment by mincrmatt12** [comment]
should be fixed by b1dbcc3.
