### ISSUE TITLE
Crash with bibliocraft

### ISSUE THREAD

**Issue by frank89722** [TeamDmfMM/Catwalks-4#2]
When I break a Framed Wooden Catwalks the game crash
https://pastebin.com/wtz2WHSg

Or I should report it to bibliocraft?

**Comment by dmf444** [comment]
Looks like a bibliocraft issue. I’ll leave this open for a bit longer, but it shouldn’t be anything on our side

**Comment by mincrmatt12** [comment]
Seconding @dmf444, no catwalks code is in the crash log as far as I can tell.

**Comment by dmf444** [comment]
Closing this issue, unless Nuchaz pushes it back to us.
