### ISSUE TITLE
All catwalks except Treated Wood Catwalk are vanished.

### ISSUE THREAD

**Issue by Snownee** [TeamDmfMM/Catwalks-4#3]

**Comment by dmf444** [comment]
Explain vanishing? On world reload? Right after placement? After 20 min of gameplay?

**Comment by Snownee** [comment]
They vanish all the time. I can only see the selection box

**Comment by dmf444** [comment]
Can you post the lastest.log?
I can't duplicate this behaviour at all

**Comment by rckymtnrfc** [comment]
They aren't vanished, they are invisible.  I just placed ladders and that appears just fine but it's like there is no texture with the catwalks.  FYI, I was not seeing this behavior with the prior version.

https://imgur.com/a/ABXVtF0

I can't Pastebin my latest.log, it's too large but I've put the file on my Drive.  https://drive.google.com/file/d/1H28tnVsM5bwIGEmtJhJu6fxW5si582R-/view?usp=sharing

**Comment by rckymtnrfc** [comment]
I did some more digging and testing and it looks like it's a conflict with Optifine E1.  I removed all my mods except catwalks-1.12.2-4.0.31 and I was able to see the catwalks again.  Added in Optifine E1 and they are invisible.

I did also test and rolled back to catwalks-1.12.2-4.0.26 with Optifine E1 and I'm able to see the catwalks.

**Comment by Snownee** [comment]
Seems there is a incompatibility with VanillaFix

**Comment by dmf444** [comment]
Any version of Catwalks including catwalks-1.12.2-4.0.36.jar and onwards, now creates a config file, with the ability to support optifine. This is disabled by default, because I have no idea what optifine does in the background, and enabling it may cause lag.
