### ISSUE TITLE
Suggestion: Holding Blow Torch shows disabled parts

### ISSUE THREAD

**Issue by hdainester** [TeamDmfMM/Catwalks-4#7]
I was thinking that it can be a bit dangerous (and annoying) that Catwalks can be completely invisible when all sides are disabled.

To overcome this all sides(parts) should become visible when holding the blowtorch in hand (or offhand).
Disabled parts should obviously still be marked as such, maybe by giving them a lower transperency.

**Comment by dmf444** [comment]
While this makes sense, I'm not too sure of the technical feasibility it. I'll try to pull it off, but there's never any guarantees.

**Comment by dmf444** [comment]
Fixed in: catwalks-1.12.2-4.0.41.jar
